export * as profileService from "./profile.service";
export * as projectService from "./project.service";
export * as skillService from "./skill.service";
export * as experienceService from "./experience.service";
export * as educationService from "./education.service";
export * as certificateService from "./certificate.service";
export * as githubService from "./github.service";
export * as contactService from "./contact.service";
export * as authService from "./auth.service";